const API_URL='https://script.google.com/macros/s/AKfycbwdRNJtcLirBBoSVQnwAGont0-E96Pp5MKU_vX331bRIoYAYNZ_xwRdrNGYWxtvGBMXpw/exec';
const $=id=>document.getElementById(id);
const searchForm=$('searchForm'),controlInput=$('controlInput'),scanBtn=$('scanBtn'),scannerCard=$('scannerCard'),closeScanner=$('closeScanner'),scannerMessage=$('scannerMessage'),resultCard=$('resultCard'),statusBadge=$('statusBadge'),resultTitle=$('resultTitle'),resultMessage=$('resultMessage'),details=$('details'),verifyAnother=$('verifyAnother'),video=$('cameraVideo');
let cameraStream=null,scannerRunning=false,scanLocked=false,barcodeDetector=null,detectorTimer=null,scannerFallback=null;
const normalize=v=>String(v??'').trim();
function escapeHtml(v){return String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));}
function field(r,...names){const wanted=names.map(n=>n.trim().replace(/\s+/g,' ').toUpperCase());for(const key of Object.keys(r||{})){const normalized=String(key).trim().replace(/\s+/g,' ').toUpperCase();if(wanted.includes(normalized)&&normalize(r[key]))return normalize(r[key]);}return '';}
function dateParts(r,prefix){const combined=field(r,prefix);if(combined)return combined;const month=field(r,`${prefix} MONTH`,prefix==='DATE ACQUIRED'?'ACQUIRED MONTH':'EXPIRATION MONTH');const day=field(r,`${prefix} DAY`,prefix==='DATE ACQUIRED'?'ACQUIRED DAY':'EXPIRATION DAY');const year=field(r,`${prefix} YEAR`,prefix==='DATE ACQUIRED'?'ACQUIRED YEAR':'EXPIRATION YEAR');return [month,day,year].filter(Boolean).join(' ');}
function parseDate(r){const raw=field(r,'EXPIRATION DATE');if(raw){const parsed=new Date(raw);if(!Number.isNaN(parsed.getTime()))return new Date(parsed.getFullYear(),parsed.getMonth(),parsed.getDate(),23,59,59);}const m=field(r,'EXPIRATION DATE MONTH','EXPIRATION MONTH'),d=field(r,'EXPIRATION DATE DAY','EXPIRATION DAY'),y=field(r,'EXPIRATION DATE YEAR','EXPIRATION YEAR');if(!m||!d||!y)return null;const months={JANUARY:0,FEBRUARY:1,MARCH:2,APRIL:3,MAY:4,JUNE:5,JULY:6,AUGUST:7,SEPTEMBER:8,OCTOBER:9,NOVEMBER:10,DECEMBER:11},mi=months[m.toUpperCase()];if(mi===undefined)return null;const date=new Date(Number(y),mi,Number(d),23,59,59);return Number.isNaN(date.getTime())?null:date;}
function getStatus(r){const s=field(r,'STATUS').toUpperCase();if(s==='INACTIVE')return'inactive';const e=parseDate(r);if(e&&e<new Date())return'expired';if(s==='ACTIVE')return'active';return'invalid';}
function showResult(data,requested){resultCard.classList.remove('hidden');const r=data.record||{};if(!data.verified){statusBadge.className='status-badge status-invalid';statusBadge.textContent='INVALID ID';resultTitle.textContent='ID Not Found';resultMessage.textContent=`No record was found for control number ${requested}.`;details.innerHTML='';return;}const map={active:['status-active','VALID / VERIFIED','This ID is active and verified.'],inactive:['status-inactive','INACTIVE ID','This ID is currently marked inactive.'],expired:['status-expired','EXPIRED ID','The expiration date has already passed.'],invalid:['status-invalid','INVALID ID','The record status could not be verified.']};const [cls,label,msg]=map[getStatus(r)]||map.invalid;statusBadge.className=`status-badge ${cls}`;statusBadge.textContent=label;resultTitle.textContent='Verification Result';resultMessage.textContent=msg;const name=[field(r,'FIRST NAME'),field(r,'MIDDLE NAME'),field(r,'SURE NAME','SURNAME','LAST NAME')].filter(Boolean).join(' ');const acquired=dateParts(r,'DATE ACQUIRED').toUpperCase();const expiration=dateParts(r,'EXPIRATION DATE').toUpperCase();const fields=[['Control Number',field(r,'CONTROL NUMBER')||requested],['Name',name],['Designation',field(r,'DESIGNATION')],['Date Acquired',acquired],['Expiration Date',expiration],['Database Status',field(r,'STATUS')]];details.innerHTML=fields.map(([l,v])=>`<div><dt>${escapeHtml(l)}</dt><dd>${escapeHtml(normalize(v)||'—')}</dd></div>`).join('');}
async function verify(control){const v=normalize(control);if(!v){controlInput.focus();return;}resultCard.classList.remove('hidden');statusBadge.className='status-badge';statusBadge.textContent='CHECKING…';resultTitle.textContent='Verifying ID';resultMessage.textContent='Connecting to the official verification database…';details.innerHTML='';try{const res=await fetch(`${API_URL}?control=${encodeURIComponent(v)}&t=${Date.now()}`,{cache:'no-store'});if(!res.ok)throw new Error(`Verification server returned ${res.status}.`);const data=await res.json();if(!data||(!data.success&&!data.verified))throw new Error(data?.message||'Verification service error.');showResult(data,v);}catch(e){statusBadge.className='status-badge status-invalid';statusBadge.textContent='ERROR';resultTitle.textContent='Verification Unavailable';resultMessage.textContent=e?.message||'Unable to connect to the verification database.';details.innerHTML='';console.error(e);}}
function extractControl(text){const v=normalize(text);if(!v)return'';try{const u=new URL(v);const c=u.searchParams.get('control')||u.searchParams.get('CONTROL')||u.searchParams.get('control_number')||u.searchParams.get('id');if(c)return normalize(c);}catch(_){}const m=v.match(/(?:CONTROL(?:\s+NUMBER)?|ID)\s*[:#=\-]?\s*([A-Za-z0-9\-]+)/i);return m?.[1]?normalize(m[1]):v;}
function cameraError(e){const n=e?.name||'';if(n==='NotAllowedError'||n==='PermissionDeniedError')return'Camera permission was denied. Tap the camera icon beside the address bar and choose Allow, then tap Scan again.';if(n==='NotFoundError'||n==='DevicesNotFoundError')return'No camera was found on this device.';if(n==='NotReadableError'||n==='TrackStartError')return'The camera is busy. Close another app using the camera and try again.';if(n==='SecurityError')return'Camera access requires HTTPS. Open the live site using its HTTPS address.';if(n==='NotSupportedError')return'This browser does not support camera access.';return`Unable to start camera (${n||'Unknown error'}). ${e?.message||''}`;}
async function startScanner(){if(scannerRunning)return;scanLocked=false;scannerCard.classList.remove('hidden');scannerMessage.textContent='Opening camera…';try{if(!window.isSecureContext)throw new DOMException('HTTPS is required.','SecurityError');if(!navigator.mediaDevices?.getUserMedia)throw new DOMException('Camera API unavailable.','NotSupportedError');cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});video.srcObject=cameraStream;await video.play();scannerRunning=true;scannerMessage.textContent='Camera is ready. Point it at the QR code.';startDetection();}catch(e){scannerRunning=false;scannerMessage.textContent=cameraError(e);console.error('Camera error:',e);}}
function startDetection(){if('BarcodeDetector' in window){try{barcodeDetector=new BarcodeDetector({formats:['qr_code']});detectNative();return;}catch(e){console.warn('BarcodeDetector unavailable',e);}}startHtml5Fallback();}
async function detectNative(){if(!scannerRunning||scanLocked||!barcodeDetector)return;try{const codes=await barcodeDetector.detect(video);if(codes.length){const control=extractControl(codes[0].rawValue);if(control){scanLocked=true;scannerMessage.textContent='QR code detected. Verifying…';controlInput.value=control;await stopScanner();await verify(control);return;}}}catch(e){console.warn('QR detection:',e);}detectorTimer=setTimeout(detectNative,250);}
async function startHtml5Fallback(){if(!window.Html5Qrcode){scannerMessage.textContent='Camera is active. QR detection is unavailable in this browser; enter the Control Number below.';return;}try{scannerFallback=new Html5Qrcode('reader');await scannerFallback.start({facingMode:'environment'},{fps:10,qrbox:{width:250,height:250}},async(text)=>{if(scanLocked)return;scanLocked=true;const control=extractControl(text);if(control){controlInput.value=control;await stopScanner();await verify(control);}},()=>{});}catch(e){console.warn('QR fallback:',e);if(scannerRunning)scannerMessage.textContent='Camera is active. Point it at the QR code or enter the Control Number manually.';}}
async function stopScanner(){scannerRunning=false;scanLocked=true;if(detectorTimer){clearTimeout(detectorTimer);detectorTimer=null;}if(scannerFallback){try{await scannerFallback.stop();}catch(_){}try{scannerFallback.clear();}catch(_){}scannerFallback=null;}if(cameraStream){cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null;}if(video)video.srcObject=null;scannerCard.classList.add('hidden');}
searchForm.addEventListener('submit',async e=>{e.preventDefault();await stopScanner();await verify(controlInput.value);});scanBtn.addEventListener('click',startScanner);closeScanner.addEventListener('click',stopScanner);verifyAnother.addEventListener('click',async()=>{await stopScanner();resultCard.classList.add('hidden');controlInput.value='';controlInput.focus();});window.addEventListener('beforeunload',()=>{if(cameraStream)cameraStream.getTracks().forEach(t=>t.stop());});const initial=new URLSearchParams(location.search).get('control');if(initial){controlInput.value=normalize(initial);verify(initial);}
